/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asociaciones.Pantallas;

import Asociaciones.Entidades.Curso;
import Asociaciones.Entidades.Estudiante;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HanselChavez
 */
public class PantallaEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form PantallaEstudiantes
     */
    int x,y;
    private Curso curso;
    public PantallaEstudiantes(Curso curso) {
        setUndecorated(true);
        initComponents();
        this.curso=curso;
        this.setLocationRelativeTo(null);
        mostrarLista();
        placeholder();
        lblEstudiantesCurso.setText(lblEstudiantesCurso.getText()
                +curso.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblEstudiantesCurso = new javax.swing.JLabel();
        txtBusquedaEstudiante = new javax.swing.JTextField();
        btnBuscarEstudiante = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEstudiantes = new javax.swing.JList<>();
        btnVolver = new javax.swing.JButton();
        btnAgregarEstudiante = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        btnllenar = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(86, 75, 163));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });

        lblEstudiantesCurso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEstudiantesCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblEstudiantesCurso.setText("Estudiantes de : ");

        txtBusquedaEstudiante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnBuscarEstudiante.setBackground(new java.awt.Color(0, 153, 51));
        btnBuscarEstudiante.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnBuscarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnBuscarEstudiante.setText("  Buscar");
        btnBuscarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });

        listEstudiantes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listEstudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEstudiantes);

        btnVolver.setBackground(new java.awt.Color(51, 51, 255));
        btnVolver.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAgregarEstudiante.setBackground(new java.awt.Color(0, 51, 204));
        btnAgregarEstudiante.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAgregarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEstudiante.setText("Agregar");
        btnAgregarEstudiante.setBorderPainted(false);
        btnAgregarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEstudiante.setInheritsPopupMenu(true);
        btnAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstudianteActionPerformed(evt);
            }
        });

        btnEliminarEstudiante.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarEstudiante.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnEliminarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEstudiante.setText("Eliminar");
        btnEliminarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });

        btnllenar.setBackground(new java.awt.Color(51, 51, 255));
        btnllenar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnllenar.setForeground(new java.awt.Color(255, 255, 255));
        btnllenar.setText("Llenar Lista");
        btnllenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnllenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnllenarActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minimize.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lblEstudiantesCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMinimize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClose))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtBusquedaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarEstudiante))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnAgregarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblEstudiantesCurso))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMinimize)
                            .addComponent(btnClose))))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBusquedaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnllenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        volverMethod();
    }//GEN-LAST:event_btnVolverActionPerformed
    private void btnAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstudianteActionPerformed
        PantallaAgregarEstudiante pantAgregarEstudia = 
        new PantallaAgregarEstudiante(curso);
        pantAgregarEstudia.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_btnAgregarEstudianteActionPerformed
    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        int k = listEstudiantes.getSelectedIndex();
        if(k!=-1){         
            String  j = listEstudiantes.getSelectedValue().trim();  
            recorrerArrayEstudiantes(j); 
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar un estudiante"
            + " de la lista","Eliminar Estudiante",
            JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed
    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        validarBusqueda();
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed
    private void btnllenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnllenarActionPerformed
       mostrarLista();
    }//GEN-LAST:event_btnllenarActionPerformed
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
       volverMethod();
    }//GEN-LAST:event_btnCloseMouseClicked
    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(PantallaGestorCursos.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked
    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x,point.y-y);
    }//GEN-LAST:event_panelMouseDragged
    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_panelMousePressed
    private void volverMethod() {
        this.dispose();
        PantallaGestorCursos pantGestorCurso = new
                PantallaGestorCursos(PantallaGestorCursos.getListaCursos());
        pantGestorCurso.setVisible(true);
    }
    private void validarBusqueda() throws HeadlessException {                
        if(!"Ingrese nombre del Estudiante".equals(txtBusquedaEstudiante.getText())){
            if(curso.getEstudiantes()[0]==null && curso.getProfesores()[1]==null){
                JOptionPane.showMessageDialog(null, "Lista de Estudiantes Vacia",
                "Buscar Estudiante", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
            recorrerlistaBuscar();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Ingresa el nombre del Estudiante",
            "Buscar Estudiante", JOptionPane.INFORMATION_MESSAGE);
        }    
    }
    private void placeholder(){
        this.txtBusquedaEstudiante.setForeground(Color.GRAY);
        this.txtBusquedaEstudiante.setText("Ingrese nombre del Estudiante");
        this.txtBusquedaEstudiante.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtBusquedaEstudiante.getText()
                    .equals("Ingrese nombre del Estudiante")) {
                    txtBusquedaEstudiante.setText("");
                    txtBusquedaEstudiante.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtBusquedaEstudiante.getText().isEmpty()) {
                    txtBusquedaEstudiante.setForeground(Color.GRAY);
                    txtBusquedaEstudiante.setText("Ingrese nombre del Estudiante");
                }
            }
        });
    }
    private void recorrerlistaBuscar() throws HeadlessException {
        String nombre = txtBusquedaEstudiante.getText();
        boolean encontrado = false;
        for (int i = 0; i < 30; i++) {           
            if (curso.getEstudiantes()[i]!=null && 
                    curso.getEstudiantes()[i].getNombre().equals(nombre)) {
                DefaultListModel model =new DefaultListModel();
                listEstudiantes.setModel(model);
                model.removeAllElements();
                model.addElement(curso.getEstudiantes()[i].toString());  
                encontrado=true;
            }       
        }
        if(encontrado==false){
            JOptionPane.showMessageDialog(null, "Estudiante no encontrado",
                    "Buscar Estudiante", JOptionPane.INFORMATION_MESSAGE);
            mostrarLista();
        }
    }
    private void recorrerArrayEstudiantes(String j) throws HeadlessException {
        for (int i = 0; i < 30; i++) {
            if(curso.getEstudiantes()[i]!=null){
                if(curso.getEstudiantes()[i].toString().equals(j)){
                    int respuesta = JOptionPane.showConfirmDialog(null,
                        "Estudiante Seleccionado: \n" + 
                        curso.getEstudiantes()[i].getNombre()
                        +"\nEstas seguro de Eliminar?",
                        "Eliminar Estudiante", JOptionPane.YES_NO_OPTION);
                    estadoEliminado(respuesta, i);
                }
            }
        }
    }
    private void estadoEliminado(int respuesta, int i) throws HeadlessException {
        if (respuesta == JOptionPane.YES_OPTION) {
            curso.getEstudiantes()[i] = null;
            mostrarLista();
            JOptionPane.showMessageDialog(null,"Estudiante Eliminado"
                    ,"Eliminar Estudiante",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"Estudiante no Eliminado"
                    ,"Eliminar Estudiante",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void mostrarLista(){
        DefaultListModel model =new DefaultListModel();        
        listEstudiantes.setModel(model); 
        model.removeAllElements();
        for (int i = 0; i < 30; i++) {
            if(curso.getEstudiantes()[i] != null)
            {
                model.addElement(curso.getEstudiantes()[i].toString());
            }
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstudiante;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnllenar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEstudiantesCurso;
    private javax.swing.JList<String> listEstudiantes;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtBusquedaEstudiante;
    // End of variables declaration//GEN-END:variables
}
