/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asociaciones.Pantallas;

import Asociaciones.Entidades.Curso;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HanselChavez
 */
public class PantallaGestorCursos extends javax.swing.JFrame {
    int x,y;
    private static List<Curso> ListaCursos = new ArrayList<Curso>();
    public static List<Curso> getListaCursos() {
        return ListaCursos;
    }
    public static void setListaCursos(List<Curso> ListaCursos) {
        PantallaGestorCursos.ListaCursos = ListaCursos;
    }   
    
    public PantallaGestorCursos(List<Curso> Lista) {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);   
        ListaCursos= Lista;
        mostrarLista();
        placeholder();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscarCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCursos = new javax.swing.JList<>();
        btnVerProfesores = new javax.swing.JButton();
        btnVerEstudiantes = new javax.swing.JButton();
        btnAgregarCurso = new javax.swing.JButton();
        btnEliminarCurso = new javax.swing.JButton();
        btnllenar = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));

        panel.setBackground(new java.awt.Color(86, 75, 163));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestor de Cursos");

        txtBusqueda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnBuscarCurso.setBackground(new java.awt.Color(0, 153, 51));
        btnBuscarCurso.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnBuscarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnBuscarCurso.setText("Buscar");
        btnBuscarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });

        listCursos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCursos);

        btnVerProfesores.setBackground(new java.awt.Color(0, 102, 51));
        btnVerProfesores.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVerProfesores.setForeground(new java.awt.Color(255, 255, 255));
        btnVerProfesores.setText("Ver Profesores");
        btnVerProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProfesoresActionPerformed(evt);
            }
        });

        btnVerEstudiantes.setBackground(new java.awt.Color(0, 102, 51));
        btnVerEstudiantes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnVerEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEstudiantes.setText("Ver Estudiantes");
        btnVerEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstudiantesActionPerformed(evt);
            }
        });

        btnAgregarCurso.setBackground(new java.awt.Color(0, 51, 204));
        btnAgregarCurso.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAgregarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCurso.setText("Agregar");
        btnAgregarCurso.setBorderPainted(false);
        btnAgregarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCurso.setInheritsPopupMenu(true);
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        btnEliminarCurso.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarCurso.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnEliminarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCurso.setText("Eliminar");
        btnEliminarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursoActionPerformed(evt);
            }
        });

        btnllenar.setBackground(new java.awt.Color(51, 51, 255));
        btnllenar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnllenar.setForeground(new java.awt.Color(255, 255, 255));
        btnllenar.setText("Listar");
        btnllenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnllenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnllenarActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minimize.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(btnMinimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btnVerProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btnAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscarCurso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnllenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMinimize)
                            .addComponent(btnClose))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCurso)
                    .addComponent(btnllenar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
       
        int k = listCursos.getSelectedIndex();
        if(k!=-1){         
            String  j = listCursos.getSelectedValue().trim();  
            for (int i = 0; i < ListaCursos.size(); i++) {
                if(ListaCursos.get(i).toString().equals(j)){ 
                    int respuesta = JOptionPane.showConfirmDialog(null,
                    "Curso Seleccionado: \n"+ListaCursos.get(i).getNombre()
                    +"\nEstas seguro de Eliminar?",
                    "Eliminar Curso", JOptionPane.YES_NO_OPTION);
                    estadoEliminado(respuesta, i);                   
                }
            } 
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar un curso"
            + " de la lista","Eliminar Curso",
            JOptionPane.INFORMATION_MESSAGE);
        }              
    }//GEN-LAST:event_btnEliminarCursoActionPerformed

    private void estadoEliminado(int respuesta, int i) throws HeadlessException {
        if (respuesta == JOptionPane.YES_OPTION) {
            ListaCursos.remove(i);
            mostrarLista();
            JOptionPane.showMessageDialog(null,"Curso Eliminado"
                    ,"Eliminar Curso",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"Curso no Eliminado"
                    ,"Eliminar Curso",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed
        PantallaAgregarCurso panAgregarCurso = new PantallaAgregarCurso();
        panAgregarCurso.setVisible(true);        
        this.dispose();   
    }//GEN-LAST:event_btnAgregarCursoActionPerformed
    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        validarBusqueda();
    }//GEN-LAST:event_btnBuscarCursoActionPerformed
    private void btnVerProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProfesoresActionPerformed
        int k = listCursos.getSelectedIndex();
        if(k!=-1){         
            String  j = listCursos.getSelectedValue().trim();  
            for (int i = 0; i < ListaCursos.size(); i++) {
                if(ListaCursos.get(i).toString().equals(j)){                                         
                    PantallaProfesores pantProfes = new 
                    PantallaProfesores(ListaCursos.get(i));
                    pantProfes.setVisible(true); 
                    this.dispose();                                             
                }
            } 
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar un curso"
            + " de la lista","Ver Profesores",
            JOptionPane.INFORMATION_MESSAGE);
        }      
    }//GEN-LAST:event_btnVerProfesoresActionPerformed
    private void btnVerEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstudiantesActionPerformed
        int k = listCursos.getSelectedIndex();
        if(k!=-1){         
            String  j = listCursos.getSelectedValue().trim();  
            for (int i = 0; i < ListaCursos.size(); i++) {
                if(ListaCursos.get(i).toString().equals(j)){                                         
                    PantallaEstudiantes pantEstudia = new 
                    PantallaEstudiantes(ListaCursos.get(i));
                    pantEstudia.setVisible(true); 
                    this.dispose();                                             
                }
            } 
        }
        else{
            JOptionPane.showMessageDialog(null,"Debe seleccionar un curso"
            + " de la lista","Ver Estudiantes",
            JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnVerEstudiantesActionPerformed
    private void btnllenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnllenarActionPerformed
        mostrarLista();
    }//GEN-LAST:event_btnllenarActionPerformed
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
       this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked
    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(PantallaGestorCursos.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked
    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_panelMousePressed
    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x,point.y-y);
    }//GEN-LAST:event_panelMouseDragged
    private void validarBusqueda() throws HeadlessException {
        if(!"Ingrese código del Curso".equals(txtBusqueda.getText())){
            if(ListaCursos.size()==0){
                JOptionPane.showMessageDialog(null, "Lista de Cursos Vacia",
                        "Buscar Curso", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                recorrerlistaBuscar();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingresa el codigo!",
                    "Buscar Curso", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void recorrerlistaBuscar() throws HeadlessException {
        String codigo = txtBusqueda.getText();
        boolean encontrado = false;
        for (int i = 0; i < ListaCursos.size(); i++) {
            if (ListaCursos.get(i).getCodigo().equals(codigo)) {
                DefaultListModel model =new DefaultListModel();
                listCursos.setModel(model);
                model.removeAllElements();
                model.addElement(ListaCursos.get(i).toString());  
                encontrado=true;
            } 
        }
        if(encontrado==false){
            JOptionPane.showMessageDialog(null, "Curso no encontrado",
                    "Buscar Curso", JOptionPane.INFORMATION_MESSAGE);
            mostrarLista();
        }
    }
    private void placeholder(){
        this.txtBusqueda.setForeground(Color.GRAY);
        this.txtBusqueda.setText("Ingrese código del Curso");
        this.txtBusqueda.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtBusqueda.getText().equals("Ingrese código del Curso")) {
                    txtBusqueda.setText("");
                    txtBusqueda.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtBusqueda.getText().isEmpty()) {
                    txtBusqueda.setForeground(Color.GRAY);
                    txtBusqueda.setText("Ingrese código del Curso");
                }
            }
        });
    }
    private void mostrarLista(){
        DefaultListModel model =new DefaultListModel();        
        listCursos.setModel(model); 
        model.removeAllElements();
        for (int i = 0; i < ListaCursos.size(); i++) {
            model.addElement(ListaCursos.get(i).toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestorCursos(ListaCursos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JButton btnVerEstudiantes;
    private javax.swing.JButton btnVerProfesores;
    private javax.swing.JButton btnllenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCursos;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
